server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/dong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dong
    password: dong

  jpa:
#    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      default_batch_fetch_size: 1000
      ddl-auto: create

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    cache: false
    mvc:
      static-path-pattern: "/static/**"

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
